name: Build main on push

# Trigger on push to "main" branch
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - Dockerfile
      - docker-entrypoint.sh
      - uwsgi.ini

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build (no push)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: false
